{
    'name':'manager user',
    'description':'quan ly va khach hang',
    'author':'ngoc hai',
    'depends':['base','product'],
    'application':True,
    'data':['security/manager_security.xml',
            'security/ir.model.access.csv',
            'views/menu_manager.xml',
            'views/agency.xml',
            'views/order.xml',
            'views/policy.xml',
            'views/product_lot.xml',
            'views/sale_program.xml',
            'views/product_cat.xml',
            'views/product.xml',
            'views/users.xml',
            ],
}